packages:
  - "apps/*"
  - "packages/*"
  - "frontend"
allowBuilds:
  '@firebase/util': false
  '@prisma/engines': true
  cpu-features: false
  esbuild: true
  msgpackr-extract: true
  prisma: false
  protobufjs: false
  ssh2: false
