export const BattleConstants = {
    MIN_PLAYERS: 2,
    DEFAULT_MAX_PLAYERS: 2,
    MAX_PLAYERS: 8,

    READY_TIMEOUT_SECONDS: 30,
    INVITATION_TIMEOUT_SECONDS: 60,
    MATCHMAKING_TIMEOUT_SECONDS: 120,

    MAX_RECONNECT_TIME_SECONDS: 60,
    MAX_SUBMISSION_PER_PLAYER: 100,
};