export const BattleConstants = {
    MIN_PLAYERS: 2,
    DEFAULT_MAX_PLAYERS: 2,
    MAX_PLAYERS: 8,
    READY_TIME: 30,
    READY_TIMEOUT_SECOND: 30,
    INVITATION_TIMEOUT_SECONDS: 60,
    MATCHMAKING_TIMEOUT_SECOND: 120,
};