export enum ErrorLayer {
  DOMAIN = "DOMAIN",

  VALIDATION = "VALIDATION",

  APPLICATION = "APPLICATION",

  INFRASTRUCTURE = "INFRASTRUCTURE",

  AUTHENTICATION = "AUTHENTICATION",

  AUTHORIZATION = "AUTHORIZATION",

  EXTERNAL = "EXTERNAL",
}